### ISSUE TITLE
Replicas hardcoded

### ISSUE THREAD

**Issue by elcomtik** [authelia/chartrepo#1]
I just found this chart, seems very promising.

I've been setting it up for the test and found that Deployment replicas are hardcoded to 1. There are also two other lines that template this setting, but they are ignored because of that hardcoded one.
https://github.com/authelia/chartrepo/blob/master/charts/authelia/templates/deployment.yaml#L34

I understand that this code is in early development, thank you in the first place for great work.

**Comment by james-d-elliott** [comment]
Hi thanks for your feedback! This is currently actually an intentional feature of the chart. The reasoning is this, if you deploy Authelia with anything that makes it stateful it's going to cause rather problematic results if you have multiple replicas.

For example if you don't use redis, the session information is stored in memory thus it literally cannot scale. Another situation is with the local SQLite3 database, which even if you can give access to with multiple containers is not supported by SQLite3 (use MySQL or Postgres). The other scenario is when using file auth instead of LDAP. Because Authelia can change the file backing the user auth and no measures are currently in place to reload that file on change, it could produce some bad results.

The solution in the short term to the file auth provider is we'll work on user authentication that uses the storage provider (SQL database). I also at some stage want to work on a k8s native session provider (CRD probably), but that's a very very low priority. 

What I may do is provide another value specifically for overriding the stateful situation and clearly note it as unsupported. But I'd be interested in what you think?

**Comment by james-d-elliott** [comment]
Relevant lines:

https://github.com/authelia/chartrepo/blob/master/charts/authelia/templates/deployment.yaml#L33-L39

https://github.com/authelia/chartrepo/blob/master/charts/authelia/templates/_helpers.tpl#L45-L64

**Comment by elcomtik** [comment]
This is quite interesting. I agree that when it is statefull, it should be limited to 1 replica. Your solution is totally right,  I wouldn't vote for overriding this logic.

There is probably some issue with helper, because my configuration is not statefull. I use deploment type Deployment, MariaDB, LDAP, Redis and it produced deployment with only one replica. 

Tomorrow I may put here some yaml files for debug purposes.

**Comment by james-d-elliott** [comment]
Yeah that's probably a bug then :) Thanks for reporting.

**Comment by james-d-elliott** [comment]
Just incorrectly placed this: https://github.com/authelia/chartrepo/commit/66b895dad9a78c11b2c0f9e416ab529fa8f02ca7#diff-ff85f7cb02a3cdb899b0eabbf855fcc22bf8bd1b5217696bdafa8e3f5250c6fe

**Comment by elcomtik** [comment]
That change fixed it, it is working like a charm now. Thanks @james-d-elliott

**Comment by 2fst4u** [comment]
Sorry to dredge up such an old issue, but this still seems to be a problem that the `replicas:` value doesn't work. What do you need to change to make it work properly?

**Comment by vasyakrg** [comment]
i have its problem too.

```
pod:
  # Must be Deployment, DaemonSet, or StatefulSet.
  kind: StatefulSet
  replicas: 3
```

but:
```
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 5
```

**Comment by vasyakrg** [comment]
> Sorry to dredge up such an old issue, but this still seems to be a problem that the `replicas:` value doesn't work. What do you need to change to make it work properly?

i fixed:
https://github.com/authelia/chartrepo/pull/218/files

**Comment by james-d-elliott** [comment]
> Sorry to dredge up such an old issue, but this still seems to be a problem that the `replicas:` value doesn't work. What do you need to change to make it work properly?

Replicas will not change from `1` if you're using stateful options like without redis, sqlite db, file auth, etc.

**Comment by james-d-elliott** [comment]
> I don't understand at all. I am using postgres, redis, and file auth in a shared location external to the cluster. My authelia pods are therefore not stateful. When I change it to daemonset it works absolutely as intended by running a pod on every node. Why would changing it to a deployment, which functionally is exactly the same as a daemonset except with only a specified number of replicas be any different?

It is stateful since there is either a single file shared between the pods or there are multiple files with different information.

**Comment by 2fst4u** [comment]
How does a single file shared between pods, in a file system off the cluster, change how they interact compared to a daemonset which works absolutely fine in this configuration?

-------- Original Message --------

**Comment by james-d-elliott** [comment]
> How does a single file shared between pods, in a file system off the cluster, change how they interact compared to a daemonset which works absolutely fine in this configuration?

It's not fine in either situation, we will probably have to fix this specific oversight. While you may not have experienced issues the issues will present themselves when users attempt to change their password occasionally.

 A file shouldn't be modified by multiple processes without some form of locking. Unfortunately there is no reasonable way to perform this in most remote filesystems. We may consider adding an unsupported option to disable this check (specifically for the file provider as it is the least likely to cause issues whereas the others will have guaranteed issues).

**Comment by 2fst4u** [comment]
Ok so that aside, if you use LDAP the replicas will work?

If yes can you suggest a good kubernetes LDAP provider? I'm only not using LDAP because I could never get it working, they all seem like legacy implementations on top of a kubernetes system.

**Comment by vasyakrg** [comment]
> Ok so that aside, if you use LDAP the replicas will work?
> 
> If yes can you suggest a good kubernetes LDAP provider? I'm only not using LDAP because I could never get it working, they all seem like legacy implementations on top of a kubernetes system.

FreeIPA.

**Comment by james-d-elliott** [comment]
There are quite a few good container options that you could look at. FreeIPA is probably one of the most difficult ones to try. I'd probably recommend [lldap](https://github.com/lldap/lldap) as it's very light without too much heartache. GLAuth is also a very solid option but I believe it's exclusively configured via a TOML file.
