### ISSUE TITLE
Secret configuration is problematic

### ISSUE THREAD

**Issue by pdf** [authelia/chartrepo#108]
Obviously storing clear-text secrets in a values file is a bad idea, however generating secrets for things like SMTP/DB/Redis/etc are not viable - one side or the other has to come first. So, clearly `existingSecret` is the way to go.

However, there are some problems with the way the chart handles secrets:
1. No documentation on the `data` structure for the `existingSecret`: through trial and error, I determined that the `key` fields under `secret.*.key` control the secret keys that should exist, but it was non-obvious from looking at the default values that these objects were relevant when specifying `existingSecret` - the upstream docs don't help in this regard either.
~~2. No way to omit certain passwords: if I'm not using a feature, I shouldn't have to provide a secret for it. Attempting to omit secrets from the `secret` values object by setting their parent keys to `null` blows up the `deployment.yaml` during templating, and omitting secrets from the `existingSecret` blows up the image at run-time, due to missing secret mounts from the deployment.~~
3. SMTP does not appear to honor the `enabledSecret` option, resulting in my experiences trying to disable passwords via the methods above, and rendering unauthenticated SMTP non-functional.
4. The `enabledSecret` fields lack documentation, and feel a little clumsy, since they conflict with the `secret.*` structure. Perhaps each object under `secret` should have an `enabled` bool instead (or I guess have handling allowing them to be set to `null`)~~, then people can disable the need to supply OIDC/Duo/etc secrets if they're not using them, in addition to things that take an optional secret, like Redis/SMTP.~~

Edited now that I've managed to generate mostly functional output, since I can see that if featuers are disabled, their secrets are also removed from the ConfigMap.

**Comment by james-d-elliott** [comment]
I'm looking at secret related issues at the moment, and using lookup for previous values. This is being done in #110.

> 1. No documentation on the `data` structure for the `existingSecret`: through trial and error, I determined that the `key` fields under `secret.*.key` control the secret keys that should exist, but it was non-obvious from looking at the default values that these objects were relevant when specifying `existingSecret` - the upstream docs don't help in this regard either.
>        ~2. No way to omit certain passwords: if I'm not using a feature, I shouldn't have to provide a secret for it. Attempting to omit secrets from the `secret` values object by setting their parent keys to `null` blows up the `deployment.yaml` during templating, and omitting secrets from the `existingSecret` blows up the image at run-time, due to missing secret mounts from the deployment.~

This section documents the secrets: https://github.com/authelia/chartrepo/tree/master/charts/authelia#secret

Can you either provide a concrete information on what would clear this documentation up for you? Alternatively maybe making a contribution since it's easy.

> 2\. SMTP does not appear to honor the `enabledSecret` option, resulting in my experiences trying to disable passwords via the methods above, and rendering unauthenticated SMTP non-functional.

Fixing this in the same PR.

> 3\. The `enabledSecret` fields lack documentation, and feel a little clumsy, since they conflict with the `secret.*` structure. Perhaps each object under `secret` should have an `enabled` bool instead (or I guess have handling allowing them to be set to `null`)~, then people can disable the need to supply OIDC/Duo/etc secrets if they're not using them, in addition to things that take an optional secret, like Redis/SMTP.~

I think maybe moving away from the extra secret section is probably better, and moving that to the specific configuration sections. Though I'm not entirely sure probably better to think about this carefully.

**Comment by pdf** [comment]
It's been a while, so my recollectoin of the details are a little hazy, but let me try to clarify.

1. I think part of the confusion for me here is that the default values for `key` look like env vars (all-caps), which is not how you would typically name YAML keys. I was left trying to work out how these mapped to the env vars in the upstream doco, until I worked out that actually the value for `key` in the `secret` section controlled which keys would be referenced from an `existingSecret`. Part of this may stem from the fact that my typical workflow is to rely on the output from `helm show values` for documentation (when documented), but it looks like there is a disparity between the README docs, and the comments included there. Though now that I know how it's meant to work, it's harder to evaluate whether the README docs are adequate either for new users.
 
Having accurate docs on the values is much easier for users to find, rather than having to track down or context-switch to the README when they're working on deploying or modifying deployments. With that in mind, it might be useful to add some comments to the first set of keys in the values, in addition to expanding the block-level comment at the top of `secret` to include the details from the README, e.g.

```yaml
  jwt:
    # The key within the secret/existingSecret that this value will be stored/referenced
    key: JWT_TOKEN
    # The value for this key. If empty and existingSecret is not specified, a random value will be generated
    value: ""
    # The filename of this secret within the mountPath
    filename: JWT_TOKEN
```

> I think maybe moving away from the extra secret section is probably better, and moving that to the specific configuration sections. Though I'm not entirely sure probably better to think about this carefully.

Yeah, not certain what the best approach is. Having the secret data co-located with the rest of the service-specific configuration makes some logical sense though, with the only curly bit being the interaction with `existingSecret`. Maybe separate secrets would make sense in that case? It's a rabbit-hole for sure.

**Comment by laurivosandi** [comment]
I have in `values.yml`:

```
secret:
  existingSecret: authelia
```

And I have specified secrets in a separate Kubernetes manifest.

This allows separating secrets from the rest.

**Comment by james-d-elliott** [comment]
Do we feel like this layout is more straight forward:

```yaml
configMap:
  authentication_backend:
    ldap:

      ## The username of the admin user.
      user: CN=Authelia,DC=example,DC=com

      ## The password of the admin user. This is configured as a secret value.
      secret:

        ## The name of the secret. Defaults to 'authelia'.
        name: ""

        ## The name of the key in the secret where the value is.
        key: LDAP_PASSWORD

        ## The name of the file injected into the container.
        file: LDAP_PASSWORD

        ## The raw value. If provided will be added to the generated secret.
        ## If not provided here then it must be provided via an existing secret.
        value: ""

        ## Set this to true if the secret already exists and you just wish to utilize it.
        existing: false

**Comment by elcomtik** [comment]
> Do we feel like this layout is more straight forward:
> 
> ```yaml
> configMap:
>   authentication_backend:
>     ldap:
> 
>       ## The username of the admin user.
>       user: CN=Authelia,DC=example,DC=com
> 
>       ## The password of the admin user. This is configured as a secret value.
>       secret:
> 
>         ## The name of the secret. Defaults to the chart release name.
>         name: ""
> 
>         ## The name of the key in the secret where the value is.
>         key: LDAP_PASSWORD
> 
>         ## The name of the file injected into the container.
>         file: LDAP_PASSWORD
> 
>         ## The raw value. If provided will be added to the generated secret.
>         ## If not provided here then it must be provided via an existing secret.
>         value: ""
> 
>         ## Set this to true if the secret already exists and you just wish to utilize it.
>         existing: false
> ```

Definitely, this makes more sense to me.

**Comment by elcomtik** [comment]
Could we add here also put here keys path, templateValue, and command, which are currently used for secret storage in HashiCorp Vault. Maybe it would make sense to prefix them by vault, eg. vaultPath.

I think, that moving secrets closer to resources they are related to is generally a good idea.

**Comment by james-d-elliott** [comment]
I can consider adding that to the list of things. I'm also considering removal of vault from the chart entirely and replacing it with a native vault configuration solution in Authelia itself. I just need to figure out a solution that will allow mapping a value appropriately if it's not on the correct path. The advantage is then the vault 

Considering the vault injector can be configured via annotations people would still be able to use it but we could remove that complexity from the chart while providing a more robust solution overall.

**Comment by elcomtik** [comment]
Native integration would be best, but I will be able cope with removal of vault injector from chart also.

Only thing it must allow is to disable usage of k8s secrets and their auto-generation.

**Comment by james-d-elliott** [comment]
Done in 0.9.0-beta1
