### ISSUE TITLE
OIDC public vs secret

### ISSUE THREAD

**Issue by laurivosandi** [authelia/chartrepo#118]
Some apps require `public: true` to function correctly, in this case the `secret` must be unset yet Helm generates the secret if it is not set. Tried various workarounds like `secret: false` and `secret: ""` but none of them worked out. Had to manually remove the generated secret from Helm generated manifest to get it working properly

PS: In general it was pretty painful to get Authelia working with Helm...

**Comment by james-d-elliott** [comment]
I've published a fix to this, if you had any direct comments on the issues with configuring the chart I'd be interested in the feedback so when we release the v1 chart / non-beta chart it will be a better experience.

**Comment by laurivosandi** [comment]
In general the configuraiton options in values.yaml - in many cases I was not sure if the chart generates the objects or references some external objects. Perhaps be more explicit in docs?
