### ISSUE TITLE
Allow not using TLSOption for Traefik IngressRoute

### ISSUE THREAD

**Issue by bnapalm** [authelia/chartrepo#130]
Traefik has a special "default" TLSOption that gets used when a specific TLSOption is not referenced from an IngressRoute. https://doc.traefik.io/traefik/v2.6/https/tls/#tls-options

I have a default TLSOption defined in a different namespace and would like to use it for all running http services, including Authelia, however, currently the chart does not support omitting the TLSOption.

I can workaround this by specifying the "default" TLSOption wtihout namespace (or in a different namespace if Traefik     allowCrossNamespace option is set), but I get an error on Traefik dashboard that the TLSOption is not found (which I think makes it fallback to the default one). It would be great if we could just not specify any TLSOption, neither existing nor a new one created by the chart.

**Comment by james-d-elliott** [comment]
For Ingreshttps://github.com/authelia/chartrepo/blob/master/charts/authelia/values.yaml#L170-L172

**Comment by bnapalm** [comment]
I tried that option. It is for specifying an existing TLSOption, and though it would seem that it should work for the "default" option as well, by just specifying the option "default" in the correct namespace, I receive errors in traefik dashboard saying that such TLSOption doesn't exist. 

`unknown TLS options: network-default@kubernetescrd`
note that my default option is named "default" and is in namespace "network", it's not a typo. And also all other IngressRoutes I have  (without the option defined at all) correctly use the expected default option and don't present any errors, so my default option works as expected.

According to the Traefik documentation linked above, the "default" option  does not have a namespace (even though of corse, technically, the kubernetes object does belong to one, but traefik itself seems to ignore it).

As mentioned above, in this case, the ingress does end up using the default option, but not without forever showing error for the respective router. I assume this is because it falls back to the default option when the defined option is deemed non-existent.

So, it seems that this option can only be properly chosen (without presenting errors) by not defining any tlsoption at all. In essence, what would satisfy this is ability to completely omit this block, including the "Option" subkey on line 53.: https://github.com/authelia/chartrepo/blob/master/charts/authelia/templates/traefikCRD/ingressRoute.yaml#L53-L59
right now I need to either specify an existing option, or a new one gets generated for me. Also, as far as I know, Traefik has its own defined default option, so the deployment should still work even if the user has no TLSOption in the IngressRoute defined, nor a manual "default" option.

**Comment by james-d-elliott** [comment]
https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute

Per their docs that should work, but looks like we made a mistake:

https://github.com/authelia/chartrepo/blob/master/charts/authelia/templates/traefikCRD/ingressRoute.yaml#L57-L58

Either way when I fix it I can probably add a method to disable it.

**Comment by james-d-elliott** [comment]
No worries!
