### ISSUE TITLE
Ingress tls secret template missing

### ISSUE THREAD

**Issue by david1412** [authelia/chartrepo#132]
Hi
I'm currently working on authelia chart, at ingress manifest i have tls.secret, the secretname is by default "authelia-tls", i dont want to have it for security purpose. I would like to use our own tls.

- I used our tls name, it worked for me becuase the authelia is running on same name space.
- the secret is already deployed before authelia .
- so i create a secret.yaml with cert and key.
- when i do helm install secret -f /secret.yaml -f /values.yaml > the ingress uses this template functionality 
- I cannot create the template and work with authelia, this doesnot support.
I would like to check with the team, if you can create the below custom template. Thanks 

 Here is the template 
 
 ```
 {{- if .Values.ingress.tls.enabled }}
apiVersion: {{ $apiVersion }}
kind: Secret
metadata:
  name: test-tls  >> this name will be used in ingress manifest
  labels:
    app: monitor > our app name
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.cert | quote }}
  tls.key: {{ .Values.secrets.key | quote }}
{{- end }}

**Comment by james-d-elliott** [comment]
This was not originally included as the commonly adopted standard within the k8s community has been that either a secrets management gitops solution managed these secrets or these secrets were generated via an ACME operator which reads annotations on ingress resources.

I have a fairly large refactor of the chart in the works and one of the areas it touches is secrets, once I have time to finish that off it's likely to be included. We would welcome a contribution from the community on this.

You can see an example of additional secrets here: https://github.com/authelia/chartrepo/blob/master/charts/authelia/templates/secretACL.yaml

Which has several helpers from here: https://github.com/authelia/chartrepo/blob/master/charts/authelia/templates/_helpers.tpl

**Comment by david1412** [comment]
Thanks for your information.
I'll try to follow the example and provide my update on it.

**Comment by james-d-elliott** [comment]
The most recent chart beta makes this possible I believe, if not let me know and I can reopen.
