### ISSUE TITLE
[Error]The encryption key is not valid against the schema check value

### ISSUE THREAD

**Issue by harishdesetti1206** [authelia/chartrepo#153]
I'm using Alpha numeric (Upper case characters) storage encryption key.
path in values: secret.storageEncryptionKey.value

time="2022-03-25T13:57:56Z" level=error msg="Failure running the storage provider startup check: the encryption key is not valid against the schema check value" stack="github.com/authelia/authelia/v4/internal/commands/root.go:92 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:78 cmdRootRun\ngithub.com/spf13/cobra@v1.4.0/command.go:860                 (*Command).execute\ngithub.com/spf13/cobra@v1.4.0/command.go:974                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.4.0/command.go:902                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10      main\nruntime/proc.go:255                                          main\nruntime/asm_amd64.s:1581                                     goexit"

Please help me if the format is right. The information about schema is not explained any where else.

**Comment by harishdesetti1206** [comment]
The problem is solved after i wipedout postgresql db and recreated it.
Probably the key is cached in postgresql side and there is mismatch between keys (because i'm trying different keys).

Closing this issue as the problem is resolved. This may help anyone facing the same type of issue in future.

**Comment by james-d-elliott** [comment]
Correct, if you use one key you can't change to another without manually invoking the change from the CLI because you need both the old and the new key in order to change keys since you need to decrypt everything first.
