### ISSUE TITLE
How to add configuration of authelia in  nginx controller in kubernetes?

### ISSUE THREAD

**Issue by harishdesetti1206** [authelia/chartrepo#155]
This is a question on how to configure authelia in nginx controller.
Its been 4 days i was trying to find example or documentation on how to add authelia configuration in nginx controller.
Not sure if there is documentation on it. 
If anyone have the links or information on it, please help me to progress.

       Environment:
       ==================
       Ingress: NGINX
       k8s: AKS
       storage: postgresql
       session: redis

Thanks.

**Comment by harishdesetti1206** [comment]
I found this online https://www.authelia.com/docs/deployment/deployment-kubernetes.html but it has information only about how to protect the ingress.

**Comment by james-d-elliott** [comment]
The notes from the helm chart output a list of annotations for `ingress-nginx`:

https://github.com/authelia/chartrepo/blob/master/charts/authelia/templates/NOTES.txt
