### ISSUE TITLE
Latest chart fails with parsing telemetry even with it disabled

### ISSUE THREAD

**Issue by tarioch** [authelia/chartrepo#175]
Since the upgrade to  0.8.37 authelia fails to start with

```
time="2022-07-01T07:10:15Z" level=error msg="Configuration: error occurred during unmarshalling configuration: 1 error(s) decoding:\n\n* error decoding 'telemetry.metrics.address': could not decode '0.0.0.0:9959' to a Address: the string '0.0.0.0:9959' does not appear to be a valid address"
time="2022-07-01T07:10:15Z" level=fatal msg="Can't continue due to the errors loading the configuration"
```

I don't have any of the metrics values configured, so this are all the default values

**Comment by james-d-elliott** [comment]
Oh weird, thought I checked everything! I'll revert it in a bit and do some more testing.

**Comment by tarioch** [comment]
Thank you very much

**Comment by roobre** [comment]
In case it helps, it seems like the default address does not match the regexp address:

https://go.dev/play/p/QUKoyRY61qS

**Comment by james-d-elliott** [comment]
Yeah evidently I didn't test that like an idiot :) I thought I did. Thinking will just go back to the  method I originally used, parse the address type as a URL and work it out from there.
