### ISSUE TITLE
Pod disruption budget is no longer beta in kubernetes 1.25

### ISSUE THREAD

**Issue by 2fst4u** [authelia/chartrepo#196]
As per https://github.com/kubernetes-sigs/metrics-server/issues/1104

This seems to be why I can't install the helm chart with poddisruptionbudget: true as it's looking for the wrong crd on kubernetes 1.25.

**Comment by james-d-elliott** [comment]
Relevant docs: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
