### ISSUE TITLE
Unable to find priorityclass setting in chart

### ISSUE THREAD

**Issue by 2fst4u** [authelia/chartrepo#202]
I may be blind but I can't seem to find a priorityclass setting in the chart. Is there one? If not, can I request one be added?

**Comment by james-d-elliott** [comment]
There is not, if you can find the docs on which API version this I can add it

**Comment by 2fst4u** [comment]
Appears to be in pod spec since v1.14 as per:

https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

I would think only the field to state an existing priorityclass name would be required, not the ability to actually create a priorityclass itself. This would be in line with the method used in other charts like this.

For example just a field called `priorityClassName` where you might put `system-node-critical`.

**Comment by james-d-elliott** [comment]
I'm trying to determine how relevant it is for us to add the priority class, or if we just do provide the name itself. Thoughts?

**Comment by 2fst4u** [comment]
Are you asking if you provide a place to put a priorityclass name or if you just put a value in the chart without being able to change it?

If the latter, it would have to be one of the defaults otherwise not everyone would have a valid value. And then there are only really high value options to use.

**Comment by james-d-elliott** [comment]
Regardless the default will not be configured. There are however two approaches we can take, we can expect someone has already created the appropriate `PriorityClass` manifest and just configure the `priorityClassName` in the PodSpec, or we can create the `PriorityClass` and assign it to the PodSpec, or both.

**Comment by 2fst4u** [comment]
Ah I see sorry. I've only ever seen a chart ask for a priorityclass name rather than actually generating a priorityclass from scratch. I would only expect the name.

And if the other approach was used you'd probably want to be able to use an existing priortyclass  name anyway if you had one.
