### ISSUE TITLE
Allow toggling certificates_directory: /certificates.

### ISSUE THREAD

**Issue by Lexikus** [authelia/chartrepo#204]
The certificates_directory is only set in the configMap when a value is inside the `certificates.values` or `certifcates.existringSecret`. This is fine, but having an `enabled: true` option, in addition, would be better. We, for instance, use sealed-secrets to provide our credentials. This means we'd rather mount the secret inside the folder than have it publically readable inside a git project.

```
{{- if (include "authelia.enabled.certificatesSecret" .) }}
    certificates_directory: /certificates
{{- end }}
```

```yaml
{{/*
Returns if we should generate the secret for certificates
*/}}
{{- define "authelia.enabled.certificatesSecret" -}}
    {{- if .Values.certificates -}}
        {{- if .Values.certificates.values -}}
            {{- true -}}
        {{- else if .Values.certificates.existingSecret -}}
            {{- true -}}
        {{- end -}}
    {{- end -}}
{{- end -}}
```

so, the change could look like this:

```
{{/*
Returns if we should generate the secret for certificates
*/}}
{{- define "authelia.enabled.certificatesSecret" -}}
    {{- if .Values.certificates -}}
        {{- if .Values.certificates.values -}}
            {{- true -}}
        {{- else if .Values.certificates.existingSecret -}}
            {{- true -}}
        {{- else if .Values.certificates.useCertificatesDirectory -}}
             {{- true -}}
        {{- end -}}
    {{- end -}}
{{- end -}}
```

**Comment by james-d-elliott** [comment]
You have not really explained why this would be used instead of just using the existingSecret option.

**Comment by Lexikus** [comment]
An alternative could be an array in that you provide the name of the secret that already exists in the cluster.  

Something like this:

```
certificates:
  secretRefs: 
    - database-certificate
    - ldap-certificate
```

This would also solve the problem of already having the secrets in a cluster.
