### ISSUE TITLE
traefik will change apiVersion in v3

### ISSUE THREAD

**Issue by pfaelzerchen** [authelia/chartrepo#212]
Hello,

Thanks for this helm chart. As I am a kubernetes beginner, authelia is by now the most demanding service to deploy. But this chart really helps, even in its current beta state. 

I just saw by chance that the current helm chart deploys ingressroutes and middlewares for traefik by
`apiVersion: traefik.containo.us/v1alpha1`

Traefik additionally supports:
`apiVersion: traefik.io/v1alpha1`

As most of my current deployment uses the latter, that does not seem to cause any trouble. However, traefik's helm chart repo mentions, that support for traefik.containo.us/v1alpha1 will be removed with traefik v3: https://doc.traefik.io/traefik/v3.0/migration/v2-to-v3/

As both apiVersions are supported with the current v2, it seems reasonable to change to the new apiVersion.

Kind regards

**Comment by james-d-elliott** [comment]
Our plan is to wait until v3 is released and perform proper testing before migrating. Our lack of support for this is a fairly clear communication that we do not intend to support it yet. That being said we'd welcome a PR which enables this migration for users with an opt-in flag.

**Comment by pfaelzerchen** [comment]
I can't contribute a PR as I am still learning things and therefore not being able to do much more than deploy helm charts with argocd. If I've found things out later (and this is still a valid issue) I'll come back.

k3s ships with traefik. The oldest mentioned release 1.24.1+k3s1 ships with v2.6.2 and therefore below 2.9. Since 1.24.7+k3s1 it is upgraded to v2.9.1. 1.25.1+k3s1 and 1.25.2+k3s1 also came with v2.6.2 of traefik. Any other k3s release is on a 2.9-version of traefik.
https://docs.k3s.io/release-notes/v1.24.X

**Comment by mnorrsken** [comment]
I try to address this in #213 , please have a look.

**Comment by mnorrsken** [comment]
I did a take on this but I missed the opt-in. I will make a new PR

**Comment by mnorrsken** [comment]
Here is the PR: #214

**Comment by james-d-elliott** [comment]
@mnorrsken thanks for the PR's, I'm still thinking about how to adequately handle this, as the original PR had a decent idea too. The only issues I had with it are:

1. A user may have both CRD's installed but may not be using the later one.
2. Some GitOps engines don't pass full capabilities to helm, and they are not available in all scenarios.

I'm trying to make a decent long term decision which will support the most configurations.

**Comment by 0x0013** [comment]
As a workaround while this is not a feature in the chart, I'm using a `sed` command as a helm post-render script:

```
#!/usr/bin/env bash
sed 's/traefik\.containo\.us/traefik.io/g'
```
Save this as a script, for example `sed-traefik-api.sh` and make it executable with `chmod +x sed-traefik-api.sh`. Then you can invoke it as a post-renderer when calling helm:

```
helm upgrade -n authelia authelia -f authelia.yaml authelia/authelia --post-renderer ./sed-traefik-api.sh
```

This will modify the resultant manifest after it is rendered, but before it is applied to your cluster.

**Comment by james-d-elliott** [comment]
Completely resolved by the above PR.
