### ISSUE TITLE
identity_providers.oidc.secret from secret?

### ISSUE THREAD

**Issue by loeken** [authelia/chartrepo#217]
I can set both OIDC_HMAC_SECRET, OIDC_PRIVATE_KEY in a secret but i dont see where i could set the identity_providers.oidc.secret i would like to save my shared secret for the oicd client in a secret so i can encrypt secrets ( using sealed secrets )

from what i can see its just not being set: https://github.com/authelia/chartrepo/blob/5eac62d65f3a8d3a154c7f0f3fba8c70ec117d45/charts/authelia/templates/secret.yaml#L40 and could be set after line 40?

I could send a PR unless there is something im missing

**Comment by james-d-elliott** [comment]
Implemented in 0.9.0-beta2. See https://github.com/authelia/chartrepo/blob/6fb885bdbdd81f53dfcc17f7d0b4afa7b4c66da0/charts/authelia/values.yaml#L1633-L1636
